esphome:
  name: airqualitydev

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 0
# Enable Home Assistant API
api:
  password: ""
  reboot_timeout: 0s
  services:
    - service: mhz19_calibrate_zero
      then:
        - mhz19.calibrate_zero: mhz19_id
ota:
  password: ""

wifi:
  networks: !include wifi/wifi.yaml
  ap:
    ssid: "AirQualityDev"
    password: "12345678"

captive_portal:

web_server:
  port: 80

 
text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP address
      id: ip
    ssid:
      name: Connected SSID
      id: ssid  

i2c:
  - id: bus_a
    scl: GPIO22
    sda: GPIO21
    #    frequency: 100kHz

uart:
 rx_pin: GPIO3
 tx_pin: GPIO1
 baud_rate: 9600

sensor:
  - platform: mhz19
    id: mhz19_id
    co2:
      name: "MH-Z19B CO2"
      id: co2
    temperature:
      name: "MH-Z19B Temperature"      
      id: mhz_temp
    update_interval: 10s
    automatic_baseline_calibration: false    
  - platform: bmp280
    i2c_id: bus_a
    temperature:
      name: "BMP280 Temperature"
      oversampling: 1x
      id: temp
    pressure:
      name: "BMP280 Pressure"
      oversampling: 1x
      id: press
      #    humidity:
      #name: "BME280 Humidity" ---- BMP does not have it!
      #oversampling: 1x
      #id: hum
    address: 0x76
    update_interval: 60s
  
  - platform: dht
    pin: GPIO13
    temperature:
      name: "DHT11 Temperature"
      id: dht_temp
    humidity:
      name: "DHT11 Humidity"
      id: dht_hum
    model: DHT11
    update_interval: 60s
